

#ifndef __MUD_PROG_H_
#define __MUD_PROG_H_

//#include "flag.h"

enum PROGTYPELIST { 
	ERROR_PROG     , IN_FILE_PROG , ACT_PROG    , SPEECH_PROG  , 
	HITPRCNT_PROG  , OGREET_PROG  , RAND_PROG   , TIME_PROG    , 
	FIGHT_PROG     , RFIGHT_PROG  , DEATH_PROG  , RDEATH_PROG  , 
	GREET_DIR_PROG , EXA_PROG     , ZAP_PROG    , RANDIW_PROG  , 
	ENTRY_PROG     , ENTER_PROG   , GREET_PROG  , RGREET_PROG  , 
	ALL_GREET_PROG , GIVE_PROG    , BRIBE_PROG  , HOUR_PROG    , 
	WEAR_PROG      , REMOVE_PROG  , SAC_PROG    , LOOK_PROG    , 
	GET_PROG       , DROP_PROG    , DAMAGE_PROG , REPAIR_PROG  , 
	SPEECHIW_PROG  , PULL_PROG    , PUSH_PROG   , SLEEP_PROG     , 
	LEAVE_PROG     , SCRIPT_PROG  , USE_PROG    , COMMAND_PROG    , 
	YELL_PROG      , SEARCH_PROG  , STEAL_PROG  , OTHERDEATH_PROG , 
	REST_PROG      ,
	MPWALK_FINISHED_PROG
};


//MAKE_FLAG (PROGTYPES, PROGTYPELIST)



#endif

